/**
 * GENERATED by scripts/chips-build-table.py — do not edit by hand.
 *
 * P(next state | phase, state) as raw COUNTS from the NayaDesk turn ledger.
 * Counts, not probabilities: the ranker needs support to decide whether a cell
 * is trustworthy, and counts stay auditable against the ledger.
 *
 * Source      naya-db-dev (dev)
 * Built       2026-07-23T13:14:25Z
 * Ledger      12707 turns total
 * Excluded    2372 legacy-composer turns (different engine, different shape)
 *             1792 `commit` turns — on dev these are the not-understood
 *             sink (speech_act=unknown in focused), not buyers committing
 * Recovered   951 turns whose goal an earlier engine wrote to
 *             resolved_intent.goal instead of action_plan.kind
 * Kept        4034 transitions
 *
 * THIS IS DEV TRAFFIC — replays and internal test conversations, not buyers.
 * Offline on a conversation-disjoint 5-fold split it predicts the next state
 * at 85.4% top-3 against 51.5% for a single fixed list (+33.8pt). That proves
 * the mechanism, not buyer preference. Regenerate on real traffic before these
 * numbers are trusted for anything a buyer sees.
 */

export const CHIP_TABLE_ID = 'ct-f786b13f7c';

export const CHIP_TABLE_META = {
  built_at: '2026-07-23T13:14:25Z',
  source: 'naya-db-dev',
  transitions: 4034,
  cells: 66,
} as const;

/** `${phase}|${state}` -> next state -> count. */
export const CHIP_TRANSITIONS: Record<string, Record<string, number>> = {
  "discover|advance": {
    "recommend": 5,
    "advance": 3,
    "shortlist_answer/emi": 1
  },
  "discover|answer": {
    "no_fit": 16,
    "answer": 12,
    "recommend": 5,
    "advance": 1
  },
  "discover|answer/amenities": {
    "recommend": 12,
    "no_fit": 5
  },
  "discover|answer/availability": {
    "recommend": 9,
    "no_fit": 7
  },
  "discover|answer/compare": {
    "recommend": 17,
    "answer/compare": 13,
    "advance": 1,
    "no_fit": 1,
    "orient": 1
  },
  "discover|answer/emi": {
    "recommend": 2,
    "no_fit": 1
  },
  "discover|answer/legal": {
    "recommend": 14,
    "no_fit": 12
  },
  "discover|answer/location": {
    "recommend": 11,
    "no_fit": 6,
    "answer/compare": 2
  },
  "discover|answer/media": {
    "no_fit": 8,
    "recommend": 6
  },
  "discover|answer/overview": {
    "recommend": 126,
    "no_fit": 66,
    "answer/compare": 17,
    "clarify_intent": 3
  },
  "discover|answer/price": {
    "recommend": 44,
    "no_fit": 23,
    "answer/compare": 20
  },
  "discover|answer/property_type": {
    "recommend": 3,
    "no_fit": 2
  },
  "discover|clarify_project_pick": {
    "clarify_project_pick": 7,
    "no_fit": 4,
    "recommend": 3,
    "advance": 1
  },
  "discover|greet": {
    "recommend": 527,
    "no_fit": 18,
    "visit_recall": 16,
    "orient": 15,
    "answer/compare": 2,
    "objection/location": 1,
    "smalltalk": 1
  },
  "discover|no_fit": {
    "no_fit": 109,
    "recommend": 27,
    "answer/compare": 3,
    "advance": 2,
    "clarify_project_pick": 1
  },
  "discover|objection/custom": {
    "recommend": 3
  },
  "discover|objection/location": {
    "orient": 1
  },
  "discover|orient": {
    "recommend": 2,
    "no_fit": 1,
    "probe": 1
  },
  "discover|recommend": {
    "recommend": 191,
    "clarify_project_pick": 39,
    "advance": 34,
    "no_fit": 29,
    "shortlist_answer/price": 16,
    "answer/compare": 13,
    "answer": 12,
    "shortlist_answer/legal": 9,
    "objection": 3,
    "shortlist_answer/availability": 3,
    "visit_recall": 1
  },
  "discover|shortlist_answer/legal": {
    "shortlist_answer/legal": 6,
    "recommend": 5,
    "advance": 3,
    "clarify_project_pick": 1
  },
  "discover|shortlist_answer/price": {
    "recommend": 6,
    "no_fit": 4,
    "shortlist_answer/price": 4,
    "shortlist_answer/legal": 1
  },
  "discover|visit_ask": {
    "answer": 3,
    "no_fit": 1,
    "recommend": 1
  },
  "discover|visit_booked": {
    "no_fit": 2
  },
  "focused|advance": {
    "answer/overview": 6,
    "answer": 2
  },
  "focused|answer": {
    "answer": 157,
    "objection": 1,
    "visit_recall": 1
  },
  "focused|answer/amenities": {
    "answer/amenities": 1,
    "hold_propose": 1
  },
  "focused|answer/availability": {
    "answer/price": 54,
    "answer/overview": 13,
    "answer/availability": 12,
    "answer/legal": 9,
    "answer/media": 7,
    "objection/custom": 7,
    "answer/location": 2
  },
  "focused|answer/compare": {
    "answer/overview": 12,
    "answer/legal": 3,
    "answer/compare": 1
  },
  "focused|answer/legal": {
    "answer/legal": 62,
    "answer/price": 23,
    "answer/media": 5,
    "answer/compare": 3,
    "answer/overview": 3,
    "answer/availability": 1,
    "answer/property_type": 1
  },
  "focused|answer/location": {
    "answer/location": 7,
    "answer/legal": 3,
    "answer/overview": 3,
    "answer/media": 1
  },
  "focused|answer/media": {
    "answer/price": 12,
    "answer/overview": 11,
    "answer/media": 10,
    "answer/legal": 1
  },
  "focused|answer/overview": {
    "answer/overview": 210,
    "answer/availability": 172,
    "answer/price": 141,
    "answer/legal": 105,
    "answer/media": 77,
    "answer/amenities": 30,
    "hold_propose": 16,
    "answer/location": 15,
    "answer/emi": 9,
    "answer/compare": 6,
    "advance": 5,
    "answer/property_type": 4,
    "visit_recall": 4,
    "objection/location": 1
  },
  "focused|answer/price": {
    "answer/overview": 27,
    "answer/price": 14,
    "answer/availability": 11,
    "answer/media": 9,
    "answer/legal": 5,
    "answer/location": 2
  },
  "focused|clarify_project_pick": {
    "answer/overview": 11,
    "answer": 2,
    "advance": 1
  },
  "focused|greet": {
    "answer/overview": 23,
    "answer": 5,
    "answer/availability": 4
  },
  "focused|hold_propose": {
    "hold_booked": 10,
    "answer/overview": 2,
    "answer/amenities": 1
  },
  "focused|no_fit": {
    "answer/legal": 4,
    "answer": 3,
    "answer/overview": 3,
    "answer/price": 3
  },
  "focused|orient": {
    "answer/price": 5
  },
  "focused|propose_visit": {
    "answer": 4
  },
  "focused|recommend": {
    "answer/overview": 428,
    "answer": 94,
    "answer/availability": 37,
    "answer/price": 33,
    "answer/legal": 15,
    "answer/location": 5,
    "answer/media": 5,
    "answer/property_type": 3,
    "answer/compare": 1
  },
  "focused|shortlist_answer/availability": {
    "answer/overview": 3
  },
  "focused|visit_ask": {
    "answer/overview": 4,
    "answer": 1
  },
  "focused|visit_booked": {
    "answer": 1,
    "answer/overview": 1
  },
  "focused|visit_propose": {
    "visit_booked": 6
  },
  "focused|visit_recall": {
    "answer": 1
  },
  "handoff|answer/overview": {
    "handoff": 10
  },
  "handoff|visit_booked": {
    "handoff": 1
  },
  "handoff|visit_propose": {
    "visit_booked": 8
  },
  "visit|advance": {
    "visit_ask": 6,
    "visit_propose": 1
  },
  "visit|answer": {
    "visit_ask": 21,
    "propose_visit": 7,
    "visit_recall": 2
  },
  "visit|answer/amenities": {
    "visit_ask": 1
  },
  "visit|answer/availability": {
    "visit_ask": 4
  },
  "visit|answer/compare": {
    "visit_ask": 18
  },
  "visit|answer/legal": {
    "visit_ask": 8
  },
  "visit|answer/location": {
    "visit_ask": 2,
    "answer/location": 1
  },
  "visit|answer/media": {
    "visit_ask": 10,
    "visit_propose": 1
  },
  "visit|answer/overview": {
    "visit_ask": 50,
    "answer/availability": 3,
    "answer/media": 3,
    "propose_visit": 2,
    "visit_propose": 1
  },
  "visit|answer/price": {
    "visit_ask": 11,
    "visit_propose": 6,
    "answer/media": 1
  },
  "visit|clarify_project_pick": {
    "visit_ask": 2
  },
  "visit|no_fit": {
    "propose_visit": 1
  },
  "visit|propose_visit": {
    "visit_ask": 5,
    "propose_visit": 1
  },
  "visit|recommend": {
    "visit_ask": 27,
    "visit_propose": 3,
    "answer/media": 1,
    "propose_visit": 1
  },
  "visit|visit_ask": {
    "visit_ask": 75,
    "visit_propose": 51,
    "answer/price": 5,
    "answer": 2,
    "answer/availability": 2,
    "answer/amenities": 1,
    "answer/legal": 1,
    "answer/location": 1,
    "answer/media": 1,
    "visit_recall": 1
  },
  "visit|visit_booked": {
    "visit_ask": 8,
    "visit_propose": 6,
    "answer/location": 1,
    "visit_recall": 1
  },
  "visit|visit_propose": {
    "visit_booked": 18,
    "visit_propose": 8,
    "visit_ask": 6,
    "answer": 1,
    "visit_recall": 1
  },
  "visit|visit_recall": {
    "visit_ask": 1
  }
};

/** Backoff level 2 — everything seen in this phase. */
export const CHIP_PHASE_PRIOR: Record<string, Record<string, number>> = {
  "discover": {
    "recommend": 1019,
    "no_fit": 315,
    "answer/compare": 70,
    "clarify_project_pick": 48,
    "advance": 45,
    "answer": 27,
    "shortlist_answer/price": 20,
    "orient": 17,
    "visit_recall": 17,
    "shortlist_answer/legal": 16,
    "clarify_intent": 3,
    "objection": 3,
    "shortlist_answer/availability": 3,
    "objection/location": 1,
    "probe": 1,
    "shortlist_answer/emi": 1,
    "smalltalk": 1
  },
  "focused": {
    "answer/overview": 760,
    "answer/price": 285,
    "answer": 270,
    "answer/availability": 237,
    "answer/legal": 207,
    "answer/media": 114,
    "answer/amenities": 32,
    "answer/location": 31,
    "hold_propose": 17,
    "answer/compare": 11,
    "hold_booked": 10,
    "answer/emi": 9,
    "answer/property_type": 8,
    "objection/custom": 7,
    "advance": 6,
    "visit_booked": 6,
    "visit_recall": 5,
    "objection": 1,
    "objection/location": 1
  },
  "handoff": {
    "handoff": 11,
    "visit_booked": 8
  },
  "visit": {
    "visit_ask": 255,
    "visit_propose": 77,
    "visit_booked": 18,
    "propose_visit": 12,
    "answer/media": 6,
    "answer/availability": 5,
    "answer/price": 5,
    "visit_recall": 5,
    "answer": 3,
    "answer/location": 3,
    "answer/amenities": 1,
    "answer/legal": 1
  }
};

/** Backoff level 3 — the whole ledger. Never empty, so ranking always terminates. */
export const CHIP_GLOBAL_PRIOR: Record<string, number> = {
  "recommend": 1019,
  "answer/overview": 760,
  "no_fit": 315,
  "answer": 300,
  "answer/price": 290,
  "visit_ask": 255,
  "answer/availability": 242,
  "answer/legal": 208,
  "answer/media": 120,
  "answer/compare": 81,
  "visit_propose": 77,
  "advance": 51,
  "clarify_project_pick": 48,
  "answer/location": 34,
  "answer/amenities": 33,
  "visit_booked": 32,
  "visit_recall": 27,
  "shortlist_answer/price": 20,
  "hold_propose": 17,
  "orient": 17,
  "shortlist_answer/legal": 16,
  "propose_visit": 12,
  "handoff": 11,
  "hold_booked": 10,
  "answer/emi": 9,
  "answer/property_type": 8,
  "objection/custom": 7,
  "objection": 4,
  "clarify_intent": 3,
  "shortlist_answer/availability": 3,
  "objection/location": 2,
  "probe": 1,
  "shortlist_answer/emi": 1,
  "smalltalk": 1
};
