import { readFileSync } from 'node:fs';
import { beforeAll, describe, expect, it } from 'vitest';
import {
  makeSemanticNlu,
  PROJECT_VECTOR_THRESHOLD,
} from '../src/engine/adapters/semantic-nlu.js';
import type { Env } from '../src/env.js';
import type { Extracted } from '../src/engine/types.js';

/**
 * Second-tenant embed gate — the REAL embedder, never a simulation.
 *
 * Every other test in this suite fakes AI.run, which means the suite can stay
 * green while the actual semantic system (bge-base + the catalog-derived
 * phrase sets + tau + the enrich gating) stops resolving a second tenant.
 * That failure mode shipped once: tenants outside a hardcoded brand list had
 * no distinctive phrases, and only a manual census caught it. This gate runs
 * the real model against the real phrase sets on every CI run.
 *
 * What is real here: the embedder (`@cf/baai/bge-base-en-v1.5` via the
 * Workers AI REST API, or a local wrangler-dev proxy — both the live model),
 * the phrase sets (tests/fixtures/second-tenant-vectors.json, generated by
 * Desk's projectPhrases from the dev catalog — the same sets the live index
 * holds), and the whole enrich path (gating regexes, clause split, tau,
 * collect). Only the Vectorize transport is in-memory: exact cosine over the
 * same vectors, same builder_id filter, same topK.
 *
 * Score bars: Vectorize quantizes — a self-query returns 0.87–0.90 where
 * exact cosine reads 1.0, so exact cosine here upper-bounds live scores by
 * roughly 0.10–0.13. POS_BAR = 0.80 therefore means "clears tau even after
 * quantization"; every committed positive calibrated >= 0.89, which also
 * leaves room for embedding-backend drift. Negatives assert < tau at exact
 * cosine, which implies below tau live a fortiori.
 *
 * Falsifiability (why a green run means something): a degenerate embedder
 * (constant vectors) sends every negative above tau — red; a dead lane or
 * broken gate leaves positives unresolved — red; a dropped builder_id filter
 * resolves the wrong tenant's project — red. Mutation-verified in U6.
 *
 * Credentials: CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID (CI, REST), or
 * EMBED_GATE_PROXY_URL (local wrangler-dev AI proxy). Without either the
 * suite SKIPS — visibly, never silently green. CI sets EMBED_GATE_REQUIRED=1
 * so missing credentials there fail instead of skipping.
 */

interface FixtureRow {
  project_id: string;
  builder_id: string;
  name: string;
  micro_market: string;
  phrases: string[];
}
interface Fixture {
  model: string;
  rows: FixtureRow[];
}

const fixture: Fixture = JSON.parse(
  readFileSync(new URL('./fixtures/second-tenant-vectors.json', import.meta.url), 'utf8'),
);

const PROXY = process.env.EMBED_GATE_PROXY_URL;
const TOKEN = process.env.CLOUDFLARE_API_TOKEN;
const ACCOUNT = process.env.CLOUDFLARE_ACCOUNT_ID;
const LIVE = Boolean(PROXY || (TOKEN && ACCOUNT));
if (process.env.EMBED_GATE_REQUIRED === '1' && !LIVE) {
  throw new Error(
    'embed gate: EMBED_GATE_REQUIRED=1 but no Workers AI credentials ' +
      '(CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID, or EMBED_GATE_PROXY_URL)',
  );
}

const TAU = PROJECT_VECTOR_THRESHOLD;
/** Exact-cosine floor for positives — tau + quantization loss + drift room. */
const POS_BAR = 0.8;
/** Top-project lead over the tenant's OTHER project, where asserted. */
const GAP_BAR = 0.05;

/** One REST/proxy call per batch, one retry — network flake is the only flake. */
async function embedBatch(texts: readonly string[]): Promise<number[][]> {
  const url =
    PROXY ?? `https://api.cloudflare.com/client/v4/accounts/${ACCOUNT}/ai/run/${fixture.model}`;
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (!PROXY) headers.authorization = `Bearer ${TOKEN}`;
  for (let attempt = 0; ; attempt++) {
    try {
      const r = await fetch(url, {
        method: 'POST',
        headers,
        body: JSON.stringify({ text: [...texts] }),
      });
      if (!r.ok) throw new Error(`workers-ai ${r.status}: ${(await r.text()).slice(0, 300)}`);
      const j = (await r.json()) as { data?: number[][]; result?: { data?: number[][] } };
      const data = j.data ?? j.result?.data;
      if (!data || data.length !== texts.length) {
        throw new Error(`embed shape mismatch: ${data?.length ?? 'none'} for ${texts.length}`);
      }
      return data;
    } catch (e) {
      if (attempt >= 1) throw e;
    }
  }
}

function cosine(a: readonly number[], b: readonly number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i]! * b[i]!;
    na += a[i]! * a[i]!;
    nb += b[i]! * b[i]!;
  }
  if (na <= 0 || nb <= 0) return 0;
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

/** Metadata mirrors Desk's writer exactly; ids follow the proj:<id>:<n> scheme. */
interface Stored {
  id: string;
  values: number[];
  metadata: { project_id: string; builder_id: string; name: string; phrase: string };
}
interface LoggedQuery {
  builderId: string;
  top?: { projectId: string; score: number };
  runnerUpOtherProject?: { projectId: string; score: number };
}

describe.skipIf(!LIVE)('second-tenant embed gate (real bge-base)', () => {
  const stored: Stored[] = [];
  const queryLog: LoggedQuery[] = [];
  let nlu: ReturnType<typeof makeSemanticNlu>;

  beforeAll(async () => {
    const texts = fixture.rows.flatMap((r) => r.phrases);
    const vectors = await embedBatch(texts);
    let i = 0;
    for (const r of fixture.rows) {
      r.phrases.forEach((phrase, n) => {
        stored.push({
          id: `proj:${r.project_id}:${n}`,
          values: vectors[i++]!,
          metadata: {
            project_id: r.project_id,
            builder_id: r.builder_id,
            name: r.name,
            phrase,
          },
        });
      });
    }

    const kvStore = new Map<string, string>();
    const env = {
      AI: {
        async run(_model: string, input: { text: string[] }) {
          return { data: await embedBatch(input.text) };
        },
      },
      PROJECT_VECTORS: {
        async query(
          vector: number[],
          opts?: { topK?: number; filter?: { builder_id?: string } },
        ) {
          const builderId = opts?.filter?.builder_id ?? '';
          const matches = stored
            .filter((v) => !builderId || v.metadata.builder_id === builderId)
            .map((v) => ({ id: v.id, score: cosine(vector, v.values), metadata: v.metadata }))
            .sort((a, b) => b.score - a.score)
            .slice(0, opts?.topK ?? 8);
          const top = matches[0];
          const other = matches.find(
            (m) => m.metadata.project_id !== top?.metadata.project_id,
          );
          queryLog.push({
            builderId,
            ...(top ? { top: { projectId: top.metadata.project_id, score: top.score } } : {}),
            ...(other
              ? { runnerUpOtherProject: { projectId: other.metadata.project_id, score: other.score } }
              : {}),
          });
          return { matches };
        },
      },
      TURN_CACHE: {
        async get(key: string, type?: string) {
          const raw = kvStore.get(key);
          if (raw === undefined) return null;
          return type === 'json' ? JSON.parse(raw) : raw;
        },
        async put(key: string, value: string) {
          kvStore.set(key, value);
        },
      },
      SIL_EMBED_MODEL: fixture.model,
      // INTENT_VECTORS deliberately absent — only the project lane runs here.
    } as unknown as Env;

    nlu = makeSemanticNlu(env);
  }, 60_000);

  /** Run one buyer turn through the real enrich; return picks + this turn's queries. */
  async function turn(text: string, builderId: string) {
    const before = queryLog.length;
    const ex: Extracted = { constraints: {} } as Extracted;
    const out = await nlu.enrich(text, builderId, ex, {
      phase: 'discover' as never,
      microMarkets: [],
    });
    return { named: out.namedProjects ?? [], queries: queryLog.slice(before) };
  }

  // Calibrated 17 Aug 2026 (exact cosine, real model): every expected score
  // >= 0.89, every negative <= 0.61. Cases within noise of a bar were dropped,
  // not tuned: "quatrer hennur" and "nrothgate quarter" tie between the two
  // Quarter siblings (shared distinctive lead - real ambiguity, U8's margin
  // bands own it), "corog hills" clears tau by only 0.07.
  const POSITIVES: Array<{ text: string; builderId: string; expected: string; minGap?: number }> = [
    // second tenant: full names
    { text: 'tell me about northgate quarter phase next', builderId: 'northgate-devco', expected: 'northgate-phase-next' },
    { text: 'tell me about northgate quarter', builderId: 'northgate-devco', expected: 'northgate-mixed' },
    // second tenant: the distinctive phrase alone — the case hardcoded brand
    // lists never served (no "vista to Northgate")
    { text: 'tell me about quarter phase next', builderId: 'northgate-devco', expected: 'northgate-phase-next', minGap: GAP_BAR },
    { text: 'tell me about quarter hennur', builderId: 'northgate-devco', expected: 'northgate-mixed', minGap: GAP_BAR },
    { text: 'tell me about coorg hills', builderId: 'verdant-estates', expected: 'verdant-coorg-hills' },
    { text: 'tell me about quay one', builderId: 'harbour-works', expected: 'harbour-quay-one' },
    // second tenant: typo of the distinctive token
    { text: 'tell me about qaurter phase next', builderId: 'northgate-devco', expected: 'northgate-phase-next' },
    // single-project tenants, full name
    { text: 'tell me about verdant coorg hills', builderId: 'verdant-estates', expected: 'verdant-coorg-hills' },
    { text: 'tell me about harbour quay one', builderId: 'harbour-works', expected: 'harbour-quay-one' },
    // flagship control: the first tenant must keep working too
    { text: 'tell me about eldorado', builderId: 'brigade-group', expected: 'brigade-eldorado' },
    { text: 'tell me about brigade eldorado', builderId: 'brigade-group', expected: 'brigade-eldorado' },
    { text: 'tell me about brigade cornerstone utopia', builderId: 'brigade-group', expected: 'brigade-cornerstone-utopia' },
  ];

  for (const c of POSITIVES) {
    it(`resolves «${c.text}» → ${c.expected} [${c.builderId}]`, async () => {
      const { named, queries } = await turn(c.text, c.builderId);
      expect(named[0]?.projectId).toBe(c.expected);
      const top = queries.at(-1)?.top;
      expect(top?.projectId).toBe(c.expected);
      expect(top!.score).toBeGreaterThanOrEqual(POS_BAR);
      if (c.minGap) {
        const other = queries.at(-1)?.runnerUpOtherProject;
        expect(top!.score - (other?.score ?? 0)).toBeGreaterThanOrEqual(c.minGap);
      }
    }, 20_000);
  }

  it('compare splits clauses and resolves both Quarter siblings', async () => {
    const { named } = await turn(
      'compare quarter phase next and quarter hennur',
      'northgate-devco',
    );
    expect(named.map((n) => n.projectId).sort()).toEqual([
      'northgate-mixed',
      'northgate-phase-next',
    ]);
  }, 20_000);

  // The builder_id filter is tenant isolation, and it must hold semantically
  // too: the other tenant's name against THIS tenant's phrases stays under
  // tau, so the filter never gets "rescued" into a wrong-project answer.
  const CROSS_TENANT: Array<{ text: string; builderId: string }> = [
    { text: 'tell me about eldorado', builderId: 'northgate-devco' },
    { text: 'tell me about quarter phase next', builderId: 'brigade-group' },
  ];
  for (const c of CROSS_TENANT) {
    it(`never resolves «${c.text}» for ${c.builderId}`, async () => {
      const { named, queries } = await turn(c.text, c.builderId);
      expect(named).toEqual([]);
      // The lane must have RUN and come back under tau — an unqueried lane
      // would make this vacuously green.
      expect(queries.length).toBeGreaterThan(0);
      expect(queries.at(-1)!.top!.score).toBeLessThan(TAU);
    }, 20_000);
  }

  // Degenerate-embedder tripwire: constant or garbage vectors push these over
  // tau. Green here means the model still separates names from noise.
  const NEGATIVES = [
    'tell me about the weather',
    'tell me about swimming pool timings',
    'tell me about metro connectivity',
    'tell me about home loan interest',
  ];
  for (const text of NEGATIVES) {
    it(`stays silent on «${text}»`, async () => {
      const { named, queries } = await turn(text, 'northgate-devco');
      expect(named).toEqual([]);
      expect(queries.length).toBeGreaterThan(0);
      expect(queries.at(-1)!.top!.score).toBeLessThan(TAU);
    }, 20_000);
  }
});
