#!/usr/bin/env python3
"""
Build the chip transition table from the NayaDesk turn ledger.

    python3 scripts/chips-build-table.py [--env dev] [--out src/chips/transition-table.ts]

Emits COUNTS, not probabilities — the ranker needs the support to decide
whether a cell is trustworthy or should back off, and counts stay auditable
against the ledger.

Two classes of row are excluded, both deliberately and both reported in the
generated header rather than dropped silently:

  legacy writers   `composer` other than converse_engine. These rows come from
                   a different engine with a different action_plan shape; their
                   transitions are not this engine's behaviour.

  commit           On dev, 1783 of 1792 `commit` turns are speech_act=unknown
                   in phase=focused — it is the not-understood sink, not a
                   buyer committing. Learning "after focus, expect commit"
                   would train the engine to predict its own failures.

The goal is read from action_plan.kind, falling back to resolved_intent.goal:
an earlier build of the engine wrote it there, and those 951 rows are real
behaviour worth keeping.
"""
import argparse, hashlib, json, subprocess, sys, datetime

SQL = """
WITH t AS (
  SELECT conversation_id, created_at, composer,
         COALESCE(json_extract(action_plan_json,'$.kind'), json_extract(resolved_intent_json,'$.goal')) kind,
         COALESCE(json_extract(action_plan_json,'$.topic'),'') topic,
         COALESCE(json_extract(snapshot_in_json,'$.phase'),'') phase
  FROM turn_ledger WHERE composer='converse_engine'
), f AS (
  SELECT * FROM t WHERE kind IS NOT NULL AND kind <> 'commit'
), s AS (
  SELECT conversation_id,
         kind || CASE WHEN topic <> '' THEN '/'||topic ELSE '' END AS state,
         LEAD(kind || CASE WHEN topic <> '' THEN '/'||topic ELSE '' END)
           OVER (PARTITION BY conversation_id ORDER BY created_at) AS next_state,
         phase AS post_phase
  FROM f
)
SELECT post_phase ph, state st, next_state nx, COUNT(*) n, COUNT(DISTINCT conversation_id) c
FROM s WHERE next_state IS NOT NULL AND post_phase IS NOT NULL AND post_phase <> ''
GROUP BY 1,2,3
"""

CENSUS = """
SELECT
  (SELECT COUNT(*) FROM turn_ledger) total,
  (SELECT COUNT(*) FROM turn_ledger WHERE composer<>'converse_engine') legacy,
  (SELECT COUNT(*) FROM turn_ledger WHERE composer='converse_engine'
     AND json_extract(action_plan_json,'$.kind')='commit') commit_sink,
  (SELECT COUNT(*) FROM turn_ledger WHERE composer='converse_engine'
     AND json_extract(action_plan_json,'$.kind') IS NULL
     AND json_extract(resolved_intent_json,'$.goal') IS NOT NULL) recovered
"""


def d1(db, env, sql):
    out = subprocess.run(
        ['npx', 'wrangler', 'd1', 'execute', db, '--env', env, '--remote', '--json',
         '--command', ' '.join(sql.split())],
        capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f'wrangler failed:\n{out.stdout}\n{out.stderr}')
    body = out.stdout[out.stdout.index('['):]
    return json.loads(body)[0]['results']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--env', default='dev')
    ap.add_argument('--db', default='naya-db-dev')
    ap.add_argument('--out', default='src/chips/transition-table.ts')
    args = ap.parse_args()

    rows = d1(args.db, args.env, SQL)
    census = d1(args.db, args.env, CENSUS)[0]

    cells, phases, glob = {}, {}, {}
    convs = 0
    for r in rows:
        key = f"{r['ph']}|{r['st']}"
        cells.setdefault(key, {})[r['nx']] = r['n']
        phases.setdefault(r['ph'], {})
        phases[r['ph']][r['nx']] = phases[r['ph']].get(r['nx'], 0) + r['n']
        glob[r['nx']] = glob.get(r['nx'], 0) + r['n']
        convs = max(convs, r['c'])
    total = sum(glob.values())

    def srt(d):
        return dict(sorted(d.items(), key=lambda kv: (-kv[1], kv[0])))

    cells = {k: srt(v) for k, v in sorted(cells.items())}
    phases = {k: srt(v) for k, v in sorted(phases.items())}
    glob = srt(glob)

    digest = hashlib.sha256(
        json.dumps([cells, phases, glob], sort_keys=True).encode()).hexdigest()[:10]
    built = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

    j = lambda o: json.dumps(o, indent=2).replace('"', "'").replace("':", "':")

    src = f"""/**
 * GENERATED by scripts/chips-build-table.py — do not edit by hand.
 *
 * P(next state | phase, state) as raw COUNTS from the NayaDesk turn ledger.
 * Counts, not probabilities: the ranker needs support to decide whether a cell
 * is trustworthy, and counts stay auditable against the ledger.
 *
 * Source      {args.db} ({args.env})
 * Built       {built}
 * Ledger      {census['total']} turns total
 * Excluded    {census['legacy']} legacy-composer turns (different engine, different shape)
 *             {census['commit_sink']} `commit` turns — on dev these are the not-understood
 *             sink (speech_act=unknown in focused), not buyers committing
 * Recovered   {census['recovered']} turns whose goal an earlier engine wrote to
 *             resolved_intent.goal instead of action_plan.kind
 * Kept        {total} transitions
 *
 * Conditioned on the phase recorded on the turn's OWN row. That column is
 * named snapshot_in but is written from the final state, so it is the phase
 * AFTER the turn — exactly what is known when chips are served. Conditioning
 * on the next row's phase instead scored 85.4% top-3, but that is leakage: the
 * next row's phase already encodes what the buyer did.
 *
 * THIS IS DEV TRAFFIC — replays and internal test conversations, not buyers.
 * Offline on a conversation-disjoint 5-fold split it predicts the next state
 * at 69.8% top-3 against 51.5% for a single fixed list (+18.3pt). That proves
 * the mechanism, not buyer preference. Regenerate on real traffic before these
 * numbers are trusted for anything a buyer sees.
 */

export const CHIP_TABLE_ID = 'ct-{digest}';

export const CHIP_TABLE_META = {{
  built_at: '{built}',
  source: '{args.db}',
  transitions: {total},
  cells: {len(cells)},
}} as const;

/** `${{phase}}|${{state}}` -> next state -> count. */
export const CHIP_TRANSITIONS: Record<string, Record<string, number>> = {json.dumps(cells, indent=2)};

/** Backoff level 2 — everything seen in this phase. */
export const CHIP_PHASE_PRIOR: Record<string, Record<string, number>> = {json.dumps(phases, indent=2)};

/** Backoff level 3 — the whole ledger. Never empty, so ranking always terminates. */
export const CHIP_GLOBAL_PRIOR: Record<string, number> = {json.dumps(glob, indent=2)};
"""
    with open(args.out, 'w') as fh:
        fh.write(src)
    print(f'wrote {args.out}')
    print(f'  id {digest}  cells {len(cells)}  transitions {total}')
    print(f'  excluded: {census["legacy"]} legacy, {census["commit_sink"]} commit-sink')
    print(f'  recovered: {census["recovered"]} rows via resolved_intent.goal')


if __name__ == '__main__':
    main()
